name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8  # 修改为所需的 Python 版本
  - numpy=1.19.0
  - scipy=1.5.0
  - scikit-learn=0.23.1
  - pillow=7.2.0
  - llvmlite=0.31.0
  - numba=0.48.0
  - cffi=1.14.0
  - protobuf=3.12.2
  - decorator=4.4.2
  - joblib=0.15.1
  - six=1.15.0
  - pip
  - pip:
      - audioread==2.1.8
      - librosa==0.6.1
      - resampy==0.2.2
      - soundfile==0.10.3.post1
      - tensorboardX==2.0
      - torch==1.4.0+cu100
      - torchvision==0.5.0+cu12.2
      - threadpoolctl==2.1.0